name: Spotify Stats Update

on:
  schedule:
    - cron: "0 */6 * * *" # cada 6 horas
  workflow_dispatch:

jobs:
  spotify:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Obtener access token de Spotify
        id: spotify_token
        run: |
          RESPONSE=$(curl -s -X POST "https://accounts.spotify.com/api/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=refresh_token" \
            -d "refresh_token=${{ secrets.SPOTIFY_REFRESH_TOKEN }}" \
            -d "client_id=${{ secrets.SPOTIFY_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.SPOTIFY_CLIENT_SECRET }}")
          
          ACCESS_TOKEN=$(echo $RESPONSE | sed -n 's/.*"access_token":"\([^"]*\)".*/\1/p')
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
          echo "Access token generado correctamente."

      - name: Obtener top tracks y recently played
        run: |
          # Top tracks
          curl -s -X GET "https://api.spotify.com/v1/me/top/tracks?limit=10" \
            -H "Authorization: Bearer $ACCESS_TOKEN" > top_tracks.json
          
          # Recently played
          curl -s -X GET "https://api.spotify.com/v1/me/player/recently-played?limit=10" \
            -H "Authorization: Bearer $ACCESS_TOKEN" > recently_played.json

      - name: Mostrar top tracks y recently played
        run: |
          echo "Top Tracks:"
          grep -E '"name"|"artists"' top_tracks.json | sed -E 's/.*"name": ?"([^"]*)".*/\1/' | awk 'NR%2{printf "%s - ", $0; next}1'
          
          echo ""
          echo "Recently Played:"
          grep -E '"name"|"artists"' recently_played.json | sed -E 's/.*"name": ?"([^"]*)".*/\1/' | awk 'NR%2{printf "%s - ", $0; next}1'

      - name: Debug archivos generados
        run: |
          echo "Archivos en el directorio actual:"
          ls -lah

      - name: Commit y push de resultados
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add top_tracks.json recently_played.json
          git commit -m "Actualización automática de Spotify Stats" || echo "No hay cambios"
          git push

