name: Spotify Stats Update

on:
  schedule:
    - cron: "0 */6 * * *" # Actualiza cada 6 horas
  workflow_dispatch:

jobs:
  spotify:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Obtener access token de Spotify
        id: spotify_token
        run: |
          RESPONSE=$(curl -s -X POST "https://accounts.spotify.com/api/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=refresh_token" \
            -d "refresh_token=${{ secrets.SPOTIFY_REFRESH_TOKEN }}" \
            -d "client_id=${{ secrets.SPOTIFY_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.SPOTIFY_CLIENT_SECRET }}")
          
          ACCESS_TOKEN=$(echo $RESPONSE | jq -r '.access_token')
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Generar estadísticas de Spotify
        uses: SANTONLA/spotify-stats-action@main
        with:
          username: silanton
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}

      - name: Commit y push de resultados
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Actualización automática de Spotify Stats" || echo "No hay cambios"
          git push

